# Generated by Django 5.0 on 2023-12-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_name', models.CharField(max_length=50)),
                ('component_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_name', models.CharField(max_length=50)),
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_description', models.TextField()),
                ('activity_component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.component')),
                ('activity_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.machine')),
                ('activity_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.schedule')),
            ],
        ),
    ]
