# Generated by Django 5.0 on 2023-12-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.status'),
        ),
    ]
