# Generated by Django 5.0 on 2023-12-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_changeseeker_changeseeker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('change_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=30)),
            ],
        ),
    ]
