# Generated by Django 5.0 on 2023-12-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_changeseeker_changed_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeseeker',
            name='Changed_activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activity'),
        ),
    ]
