# Generated by Django 5.0 on 2023-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_changeseeker_changed_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeseeker',
            name='position_number',
            field=models.IntegerField(default=0),
        ),
    ]
