# Generated by Django 5.0 on 2023-12-21 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_changeseeker_position_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
