# Generated by Django 5.0 on 2023-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_activity_activity_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_value',
            field=models.IntegerField(default=7),
        ),
    ]
