# Generated by Django 5.0 on 2023-12-21 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('user_mode', models.CharField(choices=[('A', 'administrator'), ('B', 'inspector')], default='B', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='report_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
    ]
