# Generated by Django 5.0 on 2023-12-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_users_report_report_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activity')),
                ('task_assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
